Add build directory for compose worker
grouparoo/app-example-docker pull request #12
Opened 2022-01-03 00:22 UTC by rwfeather

Without this, following the docker compose instructions in the readme will cause an error.

Fixes #10

2022-01-03 16:46 UTC, evantahler commented on docker-compose.yml
> +    build: ./
I *think* this will build the image twice, which makes this 2x slower.  Perhaps what we need here is a `depends_on` directive per https://stackoverflow.com/questions/50019948/reuse-image-built-by-one-service-in-another-service/50025029?

2022-01-03 16:46 UTC, evantahler requested changes
Can you please check if the `depends_on` directive works?

2022-01-04 20:20 UTC, rwfeather commented on docker-compose.yml
> +    build: ./
`depends_on` only modifies the runtime behavior (specifically startup sequence) : https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on

In fact, we already have a `depends_on` directive for the worker -> web on line 53, and it doesn't seem to be affecting the build time behavior.

I've done some testing and when both the web and worker include `build: ./`, it is indeed smart enough not to try building the same image twice.

2022-01-04 22:36 UTC, evantahler commented on docker-compose.yml
> +    build: ./
Awesome!

2022-01-04 22:36 UTC, evantahler approved these changes

2022-01-04 22:41 UTC, merged